Feature/survey progress
SATOCA/SATOCA pull request #53
Opened 2022-01-17 17:50 UTC by MaxWojtkow

- refactored Report storage and generation

2022-01-18 21:23 UTC, j0-s3f requested changes

2022-01-18 21:23 UTC, j0-s3f commented on Backend/src/controllers/SurveyController.ts
> +    let [min, max, a, b] = [
Please describe a and b.
You can hardly understand what this variables do.

2022-01-18 21:23 UTC, j0-s3f commented on Backend/src/controllers/SurveyController.ts
> +  static async createResponseTimeReport(/*surveyId: number, budget: number*/) {
Please add return type.

Report is a type in the entities and in the CreateReportResponseDto.

Maybe rename the one in the Dto to reference it correctly

2022-01-18 21:23 UTC, j0-s3f commented on Backend/src/controllers/SurveyController.ts
> +  static async createScoringReport(surveyId: number, budget: number) {
Please add the return type.

2022-01-18 21:23 UTC, j0-s3f commented on Backend/src/controllers/SurveyController.ts
> +  async getReports(body: CloseSurveyDto): Promise<CreateReportResponseDto> {
Please create new Dtos specific for this endpoint.

2022-01-18 21:23 UTC, j0-s3f commented on Frontend/src/Components/TrusteeLogin/TrusteeLoginContent/Reports/DisplayReport/DisplayReport.tsx
> +  const reportChart = (data: HistogramData[]) => (
Why not move the Chart to a different file as previously done.

2022-01-18 22:30 UTC, MaxWojtkow commented on Frontend/src/Components/TrusteeLogin/TrusteeLoginContent/Reports/DisplayReport/DisplayReport.tsx
> +  const reportChart = (data: HistogramData[]) => (
can still be done afterwards if necessary

2022-01-19 21:06 UTC, j0-s3f approved these changes

2022-01-19 21:06 UTC, merged